INSERT INTO USERS(EMAIL,NAME,ENABLED,PASSWORD) values ('admin','admin admin',1,'password');
INSERT INTO ROLES(AUTHORITY) VALUES('ADMIN');
INSERT INTO USERS_ROLES(USERS_EMAIL,ROLES_AUTHORITY) VALUES('admin','ADMIN');
